"""Generate reference docs from code so they cannot drift from what the system enforces.

uv run python -m app.scripts.gen_docs          # write docs/generated/*
uv run python -m app.scripts.gen_docs --check  # CI: fail if the committed docs are stale
"""

import argparse
import json
import sys
from pathlib import Path

from app.domain.policy.models import PolicyConfig
from app.domain.policy.rules import RULES
from app.domain.rbac import PERMISSION_DESCRIPTIONS, ROLE_DESCRIPTIONS, ROLE_PERMISSIONS, Permission, Role
from app.domain.workflow.purchase_request import TRANSITIONS
from app.main import app

OUT = Path(__file__).resolve().parents[3] / "docs" / "generated"
HEADER = "<!-- GENERATED by backend/app/scripts/gen_docs.py — do not edit by hand. -->\n\n"


def rbac_matrix() -> str:
    roles = list(Role)
    lines = [
        HEADER + "# RBAC matrix\n",
        "Source of truth: `backend/app/domain/rbac.py`. Seeded into the `roles`, `permissions` and "
        "`role_permissions` tables by migration; `test_rbac_catalogue_is_read_only_and_matches_code` "
        "asserts the database matches.\n",
        "Coarse permissions only. Row-level visibility (own / direct reports / departments headed / "
        "approver on the request / all) is applied in queries — see `visibility_clause` in "
        "`backend/app/modules/procurement/service.py`.\n",
        "## Roles\n",
        "| Role | Name | Purpose |",
        "|---|---|---|",
        *[f"| `{r.value}` | {ROLE_DESCRIPTIONS[r][0]} | {ROLE_DESCRIPTIONS[r][1]} |" for r in roles],
        "\n## Permission × role\n",
        "| Permission | " + " | ".join(ROLE_DESCRIPTIONS[r][0] for r in roles) + " |",
        "|---|" + "---|" * len(roles),
    ]
    for p in Permission:
        cells = " | ".join("✓" if p in ROLE_PERMISSIONS[r] else "" for r in roles)
        lines.append(f"| `{p.value}` — {PERMISSION_DESCRIPTIONS[p]} | {cells} |")
    return "\n".join(lines) + "\n"


def policy_reference() -> str:
    defaults = PolicyConfig().model_dump(mode="json")
    lines = [
        HEADER + "# Policy engine reference\n",
        "Source of truth: `backend/app/domain/policy/`. Every decision cites one of these rule IDs.\n",
        "Severities: **block** stops the request · **route** adds a human approval step · "
        "**flag** is a non-blocking signal · **info** explains an automatic outcome.\n",
        "## Rules\n",
        "| ID | Title | Description |",
        "|---|---|---|",
        *[f"| `{r.id}` | {r.title} | {r.description} |" for r in RULES.values()],
        "\n## Default policy configuration (example values, JPY)\n",
        "Each tenant starts with these values as policy v1 and publishes its own versions.\n",
        "| Setting | Default |",
        "|---|---|",
        *[f"| `{k}` | `{json.dumps(v, ensure_ascii=False)}` |" for k, v in defaults.items()],
        "\n## Purchase-request state machine\n",
        "| From | Action | Allowed targets |",
        "|---|---|---|",
    ]
    for status, actions in TRANSITIONS.items():
        for action, targets in actions.items():
            allowed = ", ".join(f"`{t.value}`" for t in sorted(targets))
            lines.append(f"| `{status.value}` | `{action.value}` | {allowed} |")
    return "\n".join(lines) + "\n"


def openapi() -> str:
    return json.dumps(app.openapi(), indent=2, ensure_ascii=False) + "\n"


FILES = {
    "rbac_matrix.md": rbac_matrix,
    "policy_reference.md": policy_reference,
    "openapi.json": openapi,
}


def main(check: bool) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, render in FILES.items():
        path, content = OUT / name, render()
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(OUT.parents[1])}")
    if stale:
        print(f"Generated docs are stale: {', '.join(stale)}. Run: uv run python -m app.scripts.gen_docs")
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    sys.exit(main(parser.parse_args().check))
