"""initial schema: identity, org structure, vendors, purchase requests, approvals, audit.

Beyond the autogenerated DDL this migration adds:
  * FKs that close the users <-> departments/vendors cycles
  * functional / GIN indexes
  * Row-Level Security policies on every tenant-owned table
  * least-privilege grants for the runtime role (audit_logs is INSERT/SELECT only)
  * the RBAC catalogue, seeded from app.domain.rbac

Revision ID: 0001
Revises:
Create Date: 2026-09-30 19:51:47.217119
"""

import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings
from app.domain.rbac import PERMISSION_DESCRIPTIONS, ROLE_DESCRIPTIONS, ROLE_PERMISSIONS

TENANT_TABLES = [
    "users",
    "user_roles",
    "invitations",
    "org_sequences",
    "departments",
    "cost_centers",
    "budgets",
    "vendors",
    "purchase_requests",
    "purchase_request_items",
    "approvals",
    "approval_policies",
    "audit_logs",
]

# Row visible/writable only when it belongs to the transaction's tenant, or when the
# session explicitly opted into the audited system bypass (login, invite acceptance).
# current_setting(..., true) returns NULL when unset -> comparison is NULL -> no rows.
TENANT_PREDICATE = (
    "org_id = NULLIF(current_setting('app.org_id', true), '')::uuid "
    "OR current_setting('app.rls_bypass', true) = 'on'"
)
ORG_PREDICATE = TENANT_PREDICATE.replace("org_id =", "id =", 1)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("fiscal_year_start_month", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12", name=op.f("ck_organizations_fiscal_month")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_permissions")),
    )
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_roles")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_audit_logs_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        sa.UniqueConstraint("seq", name=op.f("uq_audit_logs_seq")),
    )
    op.create_index("ix_audit_logs_org_action", "audit_logs", ["org_id", "action"], unique=False)
    op.create_index("ix_audit_logs_org_created", "audit_logs", ["org_id", "created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_org_entity", "audit_logs", ["org_id", "entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("head_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_departments_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("org_id", "code", name=op.f("uq_departments_org_id_code")),
    )
    op.create_index(op.f("ix_departments_org_id"), "departments", ["org_id"], unique=False)
    op.create_table(
        "org_sequences",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("next_value", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_org_sequences_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "name", name=op.f("pk_org_sequences")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_key", sa.String(length=40), nullable=False),
        sa.Column("permission_key", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_key"],
            ["permissions.key"],
            name=op.f("fk_role_permissions_permission_key_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_key"], ["roles.key"], name=op.f("fk_role_permissions_role_key_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_key", "permission_key", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=True),
        sa.Column("corporate_number", sa.String(length=13), nullable=True),
        sa.Column("invoice_registration_number", sa.String(length=14), nullable=True),
        sa.Column("categories", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("contract_status", sa.String(length=10), nullable=False),
        sa.Column("contract_expires_on", sa.Date(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_changed_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "contract_status IN ('none', 'active', 'expired')", name=op.f("ck_vendors_contract_status")
        ),
        sa.CheckConstraint(
            "invoice_registration_number IS NULL OR invoice_registration_number ~ '^T[0-9]{13}$'",
            name=op.f("ck_vendors_invoice_registration_number_format"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('unknown', 'low', 'medium', 'high')", name=op.f("ck_vendors_risk_level")
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'approved', 'suspended', 'blocked')", name=op.f("ck_vendors_status")
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 5)", name=op.f("ck_vendors_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_vendors_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_org_id"), "vendors", ["org_id"], unique=False)
    op.create_table(
        "cost_centers",
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_cost_centers_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_cost_centers_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_centers")),
        sa.UniqueConstraint("org_id", "code", name=op.f("uq_cost_centers_org_id_code")),
    )
    op.create_index(op.f("ix_cost_centers_department_id"), "cost_centers", ["department_id"], unique=False)
    op.create_index(op.f("ix_cost_centers_org_id"), "cost_centers", ["org_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_users_department_id_departments")
        ),
        sa.ForeignKeyConstraint(["manager_id"], ["users.id"], name=op.f("fk_users_manager_id_users")),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_users_org_id_organizations"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], name=op.f("fk_users_vendor_id_vendors")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(op.f("ix_users_manager_id"), "users", ["manager_id"], unique=False)
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "approval_policies",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_approval_policies_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_approval_policies_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_policies")),
        sa.UniqueConstraint("org_id", "version", name=op.f("uq_approval_policies_org_id_version")),
    )
    op.create_index(op.f("ix_approval_policies_org_id"), "approval_policies", ["org_id"], unique=False)
    op.create_index(
        "uq_approval_policies_one_active",
        "approval_policies",
        ["org_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "budgets",
        sa.Column("cost_center_id", sa.Uuid(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_budgets_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["cost_center_id"], ["cost_centers.id"], name=op.f("fk_budgets_cost_center_id_cost_centers")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_budgets_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint(
            "org_id",
            "cost_center_id",
            "fiscal_year",
            name=op.f("uq_budgets_org_id_cost_center_id_fiscal_year"),
        ),
    )
    op.create_index(op.f("ix_budgets_cost_center_id"), "budgets", ["cost_center_id"], unique=False)
    op.create_index(op.f("ix_budgets_org_id"), "budgets", ["org_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role_keys", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_invitations_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["users.id"], name=op.f("fk_invitations_invited_by_id_users")
        ),
        sa.ForeignKeyConstraint(["manager_id"], ["users.id"], name=op.f("fk_invitations_manager_id_users")),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)
    op.create_table(
        "purchase_requests",
        sa.Column("number", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("cost_center_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("estimated_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("required_by", sa.Date(), nullable=True),
        sa.Column("preferred_vendor_id", sa.Uuid(), nullable=True),
        sa.Column("is_emergency", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=True),
        sa.Column("policy_evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "category IN ('it_services', 'travel', 'facilities', 'marketing', 'professional_services', 'hardware', 'software', 'logistics', 'office_supplies', 'manufacturing')",
            name=op.f("ck_purchase_requests_category"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_approval', 'policy_blocked', 'approved', 'rejected', 'cancelled')",
            name=op.f("ck_purchase_requests_status"),
        ),
        sa.CheckConstraint("estimated_total >= 0", name=op.f("ck_purchase_requests_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers.id"],
            name=op.f("fk_purchase_requests_cost_center_id_cost_centers"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_purchase_requests_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_purchase_requests_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preferred_vendor_id"],
            ["vendors.id"],
            name=op.f("fk_purchase_requests_preferred_vendor_id_vendors"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("fk_purchase_requests_requester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_requests")),
        sa.UniqueConstraint("org_id", "number", name=op.f("uq_purchase_requests_org_id_number")),
    )
    op.create_index(
        "ix_purchase_requests_org_created", "purchase_requests", ["org_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_purchase_requests_org_department",
        "purchase_requests",
        ["org_id", "department_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_purchase_requests_org_id"), "purchase_requests", ["org_id"], unique=False)
    op.create_index(
        "ix_purchase_requests_org_requester",
        "purchase_requests",
        ["org_id", "requester_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_requests_org_status", "purchase_requests", ["org_id", "status"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_key", sa.String(length=40), nullable=False),
        sa.Column("granted_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_user_roles_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["role_key"], ["roles.key"], name=op.f("fk_user_roles_role_key_roles")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_key", name=op.f("pk_user_roles")),
    )
    op.create_index(op.f("ix_user_roles_org_id"), "user_roles", ["org_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("purchase_request_id", sa.Uuid(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("approver_role", sa.String(length=40), nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("rule_ids", sa.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('waiting', 'pending', 'approved', 'rejected', 'skipped', 'cancelled')",
            name=op.f("ck_approvals_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"], ["users.id"], name=op.f("fk_approvals_assigned_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"], ["users.id"], name=op.f("fk_approvals_decided_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_requests.id"],
            name=op.f("fk_approvals_purchase_request_id_purchase_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "purchase_request_id",
            "round",
            "sequence",
            name=op.f("uq_approvals_purchase_request_id_round_sequence"),
        ),
    )
    op.create_index(
        "ix_approvals_inbox_role", "approvals", ["org_id", "status", "approver_role"], unique=False
    )
    op.create_index(
        "ix_approvals_inbox_user", "approvals", ["org_id", "status", "assigned_user_id"], unique=False
    )
    op.create_index(op.f("ix_approvals_org_id"), "approvals", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_approvals_purchase_request_id"), "approvals", ["purchase_request_id"], unique=False
    )
    op.create_table(
        "purchase_request_items",
        sa.Column("purchase_request_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("uom", sa.String(length=20), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_request_items_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_purchase_request_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_purchase_request_items_org_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_requests.id"],
            name=op.f("fk_purchase_request_items_purchase_request_id_purchase_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_request_items")),
        sa.UniqueConstraint(
            "purchase_request_id",
            "line_no",
            name=op.f("uq_purchase_request_items_purchase_request_id_line_no"),
        ),
    )
    op.create_index(
        op.f("ix_purchase_request_items_org_id"), "purchase_request_items", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_request_items_purchase_request_id"),
        "purchase_request_items",
        ["purchase_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- FKs closing dependency cycles ----------------------------------------------------
    op.create_foreign_key(
        "fk_departments_head_user_id_users", "departments", "users", ["head_user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_vendors_status_changed_by_id_users", "vendors", "users", ["status_changed_by_id"], ["id"]
    )

    # --- Integrity & query indexes --------------------------------------------------------
    op.create_check_constraint("email_lowercase", "users", "email = lower(email)")
    op.execute(
        "CREATE UNIQUE INDEX uq_vendors_org_lower_name ON vendors (org_id, lower(name)) "
        "WHERE deleted_at IS NULL"
    )
    op.execute("CREATE INDEX ix_vendors_categories ON vendors USING gin (categories)")
    op.create_index("ix_vendors_org_status", "vendors", ["org_id", "status"])

    # --- Row-Level Security -----------------------------------------------------------
    # FORCE applies policies to the table owner too (managed Postgres often has a single
    # non-superuser owner role). Superusers / BYPASSRLS roles are never used at runtime.
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organizations FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON organizations USING ({ORG_PREDICATE}) WITH CHECK ({ORG_PREDICATE})"
    )
    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )

    # --- Least-privilege grants for the runtime role ----------------------------------------
    role = get_settings().app_db_role
    if not re.fullmatch(r"[a-z_][a-z0-9_]{0,62}", role):  # interpolated into DDL below
        raise ValueError(f"Invalid database role name: {role!r}")
    # Identifiers validated above; DDL cannot take bind parameters.
    op.execute(
        f"""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
            GRANT USAGE ON SCHEMA public TO {role};
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {role};
            GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {role};
            REVOKE ALL ON alembic_version FROM {role};
            -- Audit trail is append-only for the application.
            REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM {role};
            -- The RBAC catalogue is managed by migrations only.
            REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON roles, permissions, role_permissions FROM {role};
          END IF;
        END $$;
        """  # noqa: S608
    )

    # --- RBAC catalogue (code is the source of truth) ------------------------------------
    roles_t = sa.table("roles", sa.column("key"), sa.column("name"), sa.column("description"))
    perms_t = sa.table("permissions", sa.column("key"), sa.column("description"))
    rp_t = sa.table("role_permissions", sa.column("role_key"), sa.column("permission_key"))
    op.bulk_insert(
        roles_t,
        [{"key": r.value, "name": n, "description": d} for r, (n, d) in ROLE_DESCRIPTIONS.items()],
    )
    op.bulk_insert(perms_t, [{"key": p.value, "description": d} for p, d in PERMISSION_DESCRIPTIONS.items()])
    op.bulk_insert(
        rp_t,
        [
            {"role_key": r.value, "permission_key": p.value}
            for r, perms in ROLE_PERMISSIONS.items()
            for p in sorted(perms)
        ],
    )


def downgrade() -> None:
    op.drop_constraint("fk_vendors_status_changed_by_id_users", "vendors", type_="foreignkey")
    op.drop_constraint("fk_departments_head_user_id_users", "departments", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_request_items_purchase_request_id"), table_name="purchase_request_items")
    op.drop_index(op.f("ix_purchase_request_items_org_id"), table_name="purchase_request_items")
    op.drop_table("purchase_request_items")
    op.drop_index(op.f("ix_approvals_purchase_request_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_org_id"), table_name="approvals")
    op.drop_index("ix_approvals_inbox_user", table_name="approvals")
    op.drop_index("ix_approvals_inbox_role", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_user_roles_org_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index("ix_purchase_requests_org_status", table_name="purchase_requests")
    op.drop_index("ix_purchase_requests_org_requester", table_name="purchase_requests")
    op.drop_index(op.f("ix_purchase_requests_org_id"), table_name="purchase_requests")
    op.drop_index("ix_purchase_requests_org_department", table_name="purchase_requests")
    op.drop_index("ix_purchase_requests_org_created", table_name="purchase_requests")
    op.drop_table("purchase_requests")
    op.drop_index(op.f("ix_invitations_org_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_budgets_org_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_cost_center_id"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(
        "uq_approval_policies_one_active",
        table_name="approval_policies",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_approval_policies_org_id"), table_name="approval_policies")
    op.drop_table("approval_policies")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_index(op.f("ix_users_manager_id"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_cost_centers_org_id"), table_name="cost_centers")
    op.drop_index(op.f("ix_cost_centers_department_id"), table_name="cost_centers")
    op.drop_table("cost_centers")
    op.drop_index(op.f("ix_vendors_org_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_table("role_permissions")
    op.drop_table("org_sequences")
    op.drop_index(op.f("ix_departments_org_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index("ix_audit_logs_org_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
